In [2]:
# Dependencies
import json
import requests
import random
import os
import csv
import pandas as pd

from config import api_key
from citipy import citipy
from pprint import pprint

In [3]:
#read in the cities csv
city_data = pd.read_csv("city_data.csv")

#Add in columns needed to create our scatter plot
city_data["Cloudiness"] = ""
city_data["Country"] = ""
city_data["Date"] = ""
city_data["Humidity"] = ""
city_data["Lat"] = ""
city_data["Lng"] = ""
city_data["Max Temp"] = ""
city_data["Wind Speed"] = ""

city_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,lasa,,,,,,,,
1,faanui,,,,,,,,
2,ancud,,,,,,,,
3,lakeside,,,,,,,,
4,cabedelo,,,,,,,,
5,cidreira,,,,,,,,
6,gat,,,,,,,,
7,mopipi,,,,,,,,
8,san cristobal,,,,,,,,
9,nikolskoye,,,,,,,,
10,norman wells,,,,,,,,
11,hermanus,,,,,,,,
12,naze,,,,,,,,
13,dikson,,,,,,,,
14,butaritari,,,,,,,,
15,mar del plata,,,,,,,,
16,arman,,,,,,,,
17,carnarvon,,,,,,,,
18,mahebourg,,,,,,,,
19,victoria,,,,,,,,
20,vaini,,,,,,,,
21,tual,,,,,,,,
22,punta arenas,,,,,,,,
23,comodoro rivadavia,,,,,,,,
24,upernavik,,,,,,,,
25,arraial do cabo,,,,,,,,
26,busselton,,,,,,,,
27,rikitea,,,,,,,,
28,port hedland,,,,,,,,
29,ushuaia,,,,,,,,
...,...,...,...,...,...,...,...,...,...
470,chumikan,,,,,,,,
471,tucumcari,,,,,,,,
472,college,,,,,,,,
473,griffith,,,,,,,,
474,gigmoto,,,,,,,,
475,port hardy,,,,,,,,
476,peniche,,,,,,,,
477,pochutla,,,,,,,,
478,fort-shevchenko,,,,,,,,
479,quang ngai,,,,,,,,
480,laela,,,,,,,,
481,tabou,,,,,,,,
482,manyana,,,,,,,,
483,hobyo,,,,,,,,
484,high level,,,,,,,,
485,am timan,,,,,,,,
486,kladno,,,,,,,,
487,margate,,,,,,,,
488,abu kamal,,,,,,,,
489,panzhihua,,,,,,,,
490,saeby,,,,,,,,
491,oussouye,,,,,,,,
492,mattawa,,,,,,,,
493,grand gaube,,,,,,,,
494,police,,,,,,,,
495,praya,,,,,,,,
496,husum,,,,,,,,
497,porto velho,,,,,,,,
498,khilok,,,,,,,,
499,nishihara,,,,,,,,

In [4]:
# #generate random lat coordinates (bound between -85 and 85) and lng coordinates (bound between -180 and 180)
# lat = random.randint(-85, 85)
# lng = random.randint(-180, 180)

# #use the citypy library to generate the nearest city from the coordinates
# city = citipy.nearest_city(lat, lng).city_name



for index, row in city_data.iterrows():
    
 #set params for query URL 
    params = {
        "appid": api_key,
        "units": "imperial",
        "q": row["City"]
    }

    # Build the endpoint URL 
    base_url = "http://api.openweathermap.org/data/2.5/weather?"
    
#     try:
        # Run a request to endpoint and get url
    weather_data = requests.get(base_url, params=params)
    weather_data_json = weather_data.json()
    #print(weather_data_json['clouds']['all'])
#     except ValueError:
#         print("Error")
        #convert to json
    try:
        city_data.set_value(index, "Cloudiness", weather_data_json['clouds']['all'])
    except KeyError:
        print(f'{row["City"]} does not exist')
    
    
#city_data

/Users/danieltang/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:31: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [5]:
city_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,lasa,0,,,,,,,
1,faanui,80,,,,,,,
2,ancud,8,,,,,,,
3,lakeside,40,,,,,,,
4,cabedelo,0,,,,,,,
5,cidreira,80,,,,,,,
6,gat,48,,,,,,,
7,mopipi,92,,,,,,,
8,san cristobal,75,,,,,,,
9,nikolskoye,0,,,,,,,
10,norman wells,5,,,,,,,
11,hermanus,76,,,,,,,
12,naze,20,,,,,,,
13,dikson,48,,,,,,,
14,butaritari,8,,,,,,,
15,mar del plata,0,,,,,,,
16,arman,75,,,,,,,
17,carnarvon,0,,,,,,,
18,mahebourg,40,,,,,,,
19,victoria,75,,,,,,,
20,vaini,64,,,,,,,
21,tual,24,,,,,,,
22,punta arenas,75,,,,,,,
23,comodoro rivadavia,0,,,,,,,
24,upernavik,64,,,,,,,
25,arraial do cabo,0,,,,,,,
26,busselton,12,,,,,,,
27,rikitea,100,,,,,,,
28,port hedland,0,,,,,,,
29,ushuaia,40,,,,,,,
...,...,...,...,...,...,...,...,...,...
470,chumikan,8,,,,,,,
471,tucumcari,1,,,,,,,
472,college,20,,,,,,,
473,griffith,0,,,,,,,
474,gigmoto,88,,,,,,,
475,port hardy,40,,,,,,,
476,peniche,20,,,,,,,
477,pochutla,80,,,,,,,
478,fort-shevchenko,48,,,,,,,
479,quang ngai,100,,,,,,,
480,laela,76,,,,,,,
481,tabou,56,,,,,,,
482,manyana,90,,,,,,,
483,hobyo,0,,,,,,,
484,high level,5,,,,,,,
485,am timan,0,,,,,,,
486,kladno,0,,,,,,,
487,margate,20,,,,,,,
488,abu kamal,0,,,,,,,
489,panzhihua,0,,,,,,,
490,saeby,0,,,,,,,
491,oussouye,0,,,,,,,
492,mattawa,5,,,,,,,
493,grand gaube,40,,,,,,,
494,police,0,,,,,,,
495,praya,40,,,,,,,
496,husum,88,,,,,,,
497,porto velho,75,,,,,,,
498,khilok,8,,,,,,,
499,nishihara,0,,,,,,,

In [18]:
# city_data["Cloudiness"] = ""
# city_data["Country"] = ""
# city_data["Date"] = ""
# city_data["Humidity"] = ""
# city_data["Lat"] = ""
# city_data["Lng"] = ""
# city_data["Max Temp"] = ""
# city_data["Wind Speed"] = ""

weather_data
Cloudiness = weather_data['clouds']['all']
Country = weather_data['sys']['country']
Date = weather_data['dt']
Humidity = weather_data['main']['humidity']
Lat = weather_data['coord']['lat']
Lat = weather_data['coord']['lon']
Max_temp = weather_data['main']['temp_max']
wind_speed = weather_data['wind']['speed']

80.6

In [33]:
city_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,elko,1,,,,,,,
1,yellowknife,75,,,,,,,
2,olafsvik,75,,,,,,,
3,manokwari,75,,,,,,,
4,palabuhanratu,75,,,,,,,
5,cape town,75,,,,,,,
6,clyde river,75,,,,,,,
7,punta arenas,75,,,,,,,
8,esperance,75,,,,,,,
9,ponta do sol,75,,,,,,,
10,kapaa,75,,,,,,,
11,puerto ayora,75,,,,,,,
12,talnakh,75,,,,,,,
13,ancud,75,,,,,,,
14,tilichiki,75,,,,,,,
15,qaanaaq,75,,,,,,,
16,tura,75,,,,,,,
17,busselton,75,,,,,,,
18,bredasdorp,75,,,,,,,
19,ambon,75,,,,,,,
20,hermanus,75,,,,,,,
21,georgetown,75,,,,,,,
22,port alfred,75,,,,,,,
23,mwingi,75,,,,,,,
24,lata,75,,,,,,,
25,evensk,75,,,,,,,
26,kununurra,75,,,,,,,
27,kifri,75,,,,,,,
28,karratha,75,,,,,,,
29,cabedelo,75,,,,,,,
...,...,...,...,...,...,...,...,...,...
470,santiago,75,,,,,,,
471,ratnagiri,75,,,,,,,
472,charters towers,75,,,,,,,
473,morant bay,75,,,,,,,
474,yulara,75,,,,,,,
475,puerto escondido,75,,,,,,,
476,varkkallai,75,,,,,,,
477,morondava,75,,,,,,,
478,tripoli,75,,,,,,,
479,saleaula,75,,,,,,,
480,amahai,75,,,,,,,
481,kargopol,75,,,,,,,
482,duvan,75,,,,,,,
483,pudozh,75,,,,,,,
484,broome,75,,,,,,,
485,camana,75,,,,,,,
486,mangrol,75,,,,,,,
487,yamada,75,,,,,,,
488,haines junction,75,,,,,,,
489,te anau,75,,,,,,,
490,riyadh,75,,,,,,,
491,tolaga bay,75,,,,,,,
492,valparaiso,75,,,,,,,
493,medea,75,,,,,,,
494,naze,75,,,,,,,
495,brae,75,,,,,,,
496,longkou,75,,,,,,,
497,requena,75,,,,,,,
498,tahoua,75,,,,,,,
499,berikulskiy,75,,,,,,,

In [18]:
 params = {
        "appid": api_key,
        "units": "imperial",
        "q": "olafsvik"
    }

# Build the endpoint URL 
base_url = "http://api.openweathermap.org/data/2.5/weather?"
# Run a request to endpoint and get url
weather_data = requests.get(base_url, params=params).json()

#convert to json
weather_data

{'cod': '404', 'message': 'city not found'}

In [33]:

params = {
    "appid": api_key,
    "units": "imperial",
    "q": "praya"
}

# Build the endpoint URL 
base_url = "http://api.openweathermap.org/data/2.5/weather?"

try:
    # Run a request to endpoint and get url
    weather_data = requests.get(base_url, params=params)
    weather_data.raise_for_status()
except requests.exceptions.RequestException as e:
    print(e)
    print("No City Exists!")
weather_data.json()

{'base': 'stations',
 'clouds': {'all': 40},
 'cod': 200,
 'coord': {'lat': -8.71, 'lon': 116.27},
 'dt': 1522463400,
 'id': 1630662,
 'main': {'humidity': 62,
  'pressure': 1010,
  'temp': 87.8,
  'temp_max': 87.8,
  'temp_min': 87.8},
 'name': 'Praya',
 'sys': {'country': 'ID',
  'id': 8001,
  'message': 0.1633,
  'sunrise': 1522448299,
  'sunset': 1522491589,
  'type': 1},
 'visibility': 10000,
 'weather': [{'description': 'scattered clouds',
   'icon': '03d',
   'id': 802,
   'main': 'Clouds'}],
 'wind': {'deg': 360, 'speed': 3.36}}