Your objective is to build a series of scatter plots to showcase the following relationships:

* Temperature (F) vs. Latitude
* Humidity (%) vs. Latitude
* Cloudiness (%) vs. Latitude
* Wind Speed (mph) vs. Latitude

* Randomly select **at least** 500 unique (non-repeat) cities based on latitude and longitude.
* Perform a weather check on each of the cities using a series of successive API calls. 
* Include a print log of each city as it's being processed with the city number, city name, and requested URL.
* Save both a CSV of all data retrieved and png images for each scatter plot.

In [110]:
# Dependencies
import json
import requests
import random
import os
import csv
import pandas as pd
import numpy as np

from config import api_key
from citipy import citipy
from pprint import pprint

In [139]:
#Create an empty list to store 500 random cities
city_list = []

#write the city list to csv
with open('city_data.csv', 'w', newline='') as newfile:  
        
    #initialize csv writer
    csvwriter = csv.writer(newfile, delimiter=',')  

    #write the city list to csv
    csvwriter.writerow(["City"])

    while len(city_list) < 500:  

        #generate random lat coordinates (bound between -90 and 90) and lng coordinates (bound between -180 and 180)
        lat = random.uniform(-90,90)
        lng = random.uniform(-180,180)

        #use the citypy library to generate the nearest city from the coordinates
        try:
            city = citipy.nearest_city(lat, lng).city_name
        except ValueError:
            print("No City Exists!")

        #append city to list
        if city not in city_list:
            city_list.append(city)
            #write the city to csv
            csvwriter.writerow([city])

In [142]:
#read in the cities csv
city_data = pd.read_csv("city_data.csv")

#Add in columns needed to create our scatter plot
city_data["Cloudiness"] = ""
city_data["Country"] = ""
city_data["Date"] = ""
city_data["Humidity"] = ""
city_data["Lat"] = ""
city_data["Lng"] = ""
city_data["Max Temp"] = ""
city_data["Wind Speed"] = ""

city_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,elko,,,,,,,,
1,yellowknife,,,,,,,,
2,olafsvik,,,,,,,,
3,manokwari,,,,,,,,
4,palabuhanratu,,,,,,,,
5,cape town,,,,,,,,
6,clyde river,,,,,,,,
7,punta arenas,,,,,,,,
8,esperance,,,,,,,,
9,ponta do sol,,,,,,,,
10,kapaa,,,,,,,,
11,puerto ayora,,,,,,,,
12,talnakh,,,,,,,,
13,ancud,,,,,,,,
14,tilichiki,,,,,,,,
15,qaanaaq,,,,,,,,
16,tura,,,,,,,,
17,busselton,,,,,,,,
18,bredasdorp,,,,,,,,
19,ambon,,,,,,,,
20,hermanus,,,,,,,,
21,georgetown,,,,,,,,
22,port alfred,,,,,,,,
23,mwingi,,,,,,,,
24,lata,,,,,,,,
25,evensk,,,,,,,,
26,kununurra,,,,,,,,
27,kifri,,,,,,,,
28,karratha,,,,,,,,
29,cabedelo,,,,,,,,
...,...,...,...,...,...,...,...,...,...
470,santiago,,,,,,,,
471,ratnagiri,,,,,,,,
472,charters towers,,,,,,,,
473,morant bay,,,,,,,,
474,yulara,,,,,,,,
475,puerto escondido,,,,,,,,
476,varkkallai,,,,,,,,
477,morondava,,,,,,,,
478,tripoli,,,,,,,,
479,saleaula,,,,,,,,
480,amahai,,,,,,,,
481,kargopol,,,,,,,,
482,duvan,,,,,,,,
483,pudozh,,,,,,,,
484,broome,,,,,,,,
485,camana,,,,,,,,
486,mangrol,,,,,,,,
487,yamada,,,,,,,,
488,haines junction,,,,,,,,
489,te anau,,,,,,,,
490,riyadh,,,,,,,,
491,tolaga bay,,,,,,,,
492,valparaiso,,,,,,,,
493,medea,,,,,,,,
494,naze,,,,,,,,
495,brae,,,,,,,,
496,longkou,,,,,,,,
497,requena,,,,,,,,
498,tahoua,,,,,,,,
499,berikulskiy,,,,,,,,

In [61]:

with open('cities_url_log.csv', 'w', newline='') as newfile:
        
    #initialize csv writer
    csvwriter = csv.writer(newfile, delimiter=',')

    csvwriter.writerow(["Beginning Data Retrieval"])
    csvwriter.writerow(["----------------------------"])

    #Loop 500 times to generate 500 random lat/lng coordinates and store them in params 
    for index, row in city_data.iterrows():
        
        #set params for query URL 
        params = {
            "appid": api_key,
            "units": "imperial",
            "q": row["City"]
        }

        # Build the endpoint URL 
        base_url = "http://api.openweathermap.org/data/2.5/weather?"

        # Run a request to endpoint and get url
        weather_data = requests.get(base_url, params=params)
        
        csvwriter.writerow([f"Processing City {index+1} | {city}"])
        csvwriter.writerow([weather_data.url])

In [69]:
#Read in the list of cities
city_pd = pd.read_csv('cities')


#Loop 500 times to generate 500 random lat/lng coordinates and store them in params 
for x in range(0,1):

    #generate random lat coordinates (bound between -85 and 85) and lng coordinates (bound between -180 and 180)
    lat = random.randint(-85, 85)
    lng = random.randint(-180, 180)

    #use the citypy library to generate the nearest city from the coordinates
    city = citipy.nearest_city(lat, lng).city_name

    #set params for query URL 
    params = {
        "appid": api_key,
        "units": "imperial",
        "q": city
    }

    # Build the endpoint URL 
    base_url = "http://api.openweathermap.org/data/2.5/weather?"

    # Run a request to endpoint and get url
    weather_data = requests.get(base_url, params=params).json()
    pprint(weather_data)

{'base': 'stations',
 'clouds': {'all': 36},
 'cod': 200,
 'coord': {'lat': -39.19, 'lon': 173.88},
 'dt': 1522426591,
 'id': 2185763,
 'main': {'grnd_level': 1020.27,
          'humidity': 100,
          'pressure': 1020.27,
          'sea_level': 1029.78,
          'temp': 59.6,
          'temp_max': 59.6,
          'temp_min': 59.6},
 'name': 'Okato',
 'sys': {'country': 'NZ',
         'message': 0.1634,
         'sunrise': 1522348630,
         'sunset': 1522390797},
 'weather': [{'description': 'scattered clouds',
              'icon': '03n',
              'id': 802,
              'main': 'Clouds'}],
 'wind': {'deg': 252.007, 'speed': 7.96}}

In [92]:

city_data = pd.DataFrame({"City" : "", 
                        "Cloudiness" : "",
                        "Country" : "",
                        "Date" : "",
                        "Humidity" : "",
                        "Lat" : "",
                        "Lng" : "",
                        "Max Temp" : "",
                        "Wind Speed" : ""}, index=[0])

  City Cloudiness Country Date Humidity Lat Lng Max Temp Wind Speed
0

In [125]:
#generate random lat coordinates (bound between -85 and 85) and lng coordinates (bound between -180 and 180)
lat = np.random.uniform(low=-85, high=85, size=(5,))
lng = np.random.uniform(low=-180, high=180, size=(5,))

print(lat)
print(lng)
#Loop 500 times to generate 500 random cities and export to csv
for lat, lng in zip(lat,lng):
    print(f'lat:{lat}')
    print(f'lat:{lng}')

[ 82.1104943  -83.80146767  40.15910103   4.43241271 -12.34396691]
[-114.40631999  -92.86488197    9.52642588   72.57357167  173.9116713 ]
lat:82.11049430286766
lat:-114.4063199914269
lat:-83.80146767407706
lat:-92.86488197414482
lat:40.15910102668808
lat:9.526425881383545
lat:4.432412709014315
lat:72.57357167304261
lat:-12.343966914490238
lat:173.91167130164666

[-51,
 -62,
 1,
 14,
 -40,
 60,
 31,
 75,
 79,
 -31,
 -12,
 70,
 9,
 18,
 59,
 -84,
 -17,
 -23,
 -36,
 74,
 -49,
 37,
 -85,
 -39,
 -35,
 52,
 84,
 71,
 62,
 -57,
 -13,
 -27,
 61,
 -72,
 33,
 -14,
 -7,
 -6,
 6,
 -68,
 -42,
 76,
 36,
 -58,
 -75,
 -71,
 67,
 7,
 38,
 -16]